### PR TITLE
Add stern-pinball-arcade

### PR DESCRIPTION
**Pull request by HorrorTroll**

### CODE REVIEW

**Comment by AcK77** [comment]
Are you sure about the TitleId you used and about the state_emu_version too?
Can you resize the boxart at the good size too (as the Readme said)?
Thanks!

**Comment by HorrorTroll** [comment]
yes the state_emu_version was on build 1.0.966

**Comment by AcK77** [comment]
Yes but this version is from a PR and not from the master... Feedback are accepted just for master, because if a PR is never merged, the feedback is false.

**Comment by HorrorTroll** [comment]
ohh, didn't know that. Fixing all done now!

**Comment by AcK77** [comment]
Now you know ;)! Thanks!

**Pull request merged**
