### PR TITLE
Add asg-striker-pack

### PR DESCRIPTION
**Pull request by HorrorTroll**

### CODE REVIEW

**Comment by AcK77** [comment]
Are sure it’s a 32bits game? Because if the game tried to access unmapped address doesn’t mean it’s a 32bits game. 

As your others PR, could you provide some log?

**Comment by HorrorTroll** [comment]
It's actually 32-bit, because this games was released on 3DS first

**Comment by AcK77** [comment]
Any log?

**Comment by HorrorTroll** [comment]
https://pastebin.com/nUgbF3L6

The log here

**Comment by AcK77** [comment]
Thanks for the log!
Seems good to me. But please don't forget to resize the boxart as your others PR!

**Pull request merged**
