### PR TITLE
Add 88-heroes

### PR DESCRIPTION
**Pull request by HorrorTroll**

### CODE REVIEW

**Comment by AcK77** [comment]
Can you specify where the exception is occurred? Btw, the last stub is a little helpful.

Next time you do a PR, if you can send a pastebin (or equivalent) with Ryujinx log inside, it would be great!

**Comment by HorrorTroll** [comment]
Full log: https://pastebin.com/9KMFy2PW

**Comment by AcK77** [comment]
Thanks for the log.
Please can you resize the boxart to the right size as it's said in the Readme?
The error is strange here since you haven't change the Debug Log parameter in the .conf file of the emulator... At least, it's maybe a thread problem, or a stub who is called in a thread.

**Comment by HorrorTroll** [comment]
Done

**Comment by AcK77** [comment]
Sorry but your commit said 1149x710... The Readme say: Please do use a clean picture sized at 300px x 486px (or around that).

**Comment by HorrorTroll** [comment]
Please ensure you have a full screenshot of the Ryujinx with the game displaying; please only use a .png format only. It must be 1280px x 720px (or around that).

But i saw this on readme?

**Comment by AcK77** [comment]
It’s the screenshot.png part who said that! The boxart.png one said what I told you before!

**Pull request merged**
